name         = "PengCheng Guo"
display_name  = "PengCheng Guo"
image         = "/assets/images/people/pengcheng_guo.jpg"
profile_url   = ""
role          = "PhD 2012, UF"
bio           = ""
heading_level = "h3"
sort_order    = 2
