name         = "Althea Moorhead"
display_name  = "Althea Moorhead"
image         = "/assets/images/people/althea_moorhead.jpg"
profile_url   = ""
role          = "Postdoc, UF\nSpace Scientist, NASA Marshall Space Flight Center"
bio           = ""
heading_level = "h3"
sort_order    = 2

[[links]]
url   = "https://www.linkedin.com/in/althea-moorhead-53659749"
title = "LinkedIn"
icon  = "fa-brands fa-linkedin"

[[links]]
url   = "https://scholar.google.com/citations?user=pcCAvxAAAAAJ&hl=en"
title = "Google Scholar"
icon  = "fa-solid fa-graduation-cap"
