name         = "Aaron Boley"
display_name  = "Aaron Boley"
image         = "/assets/images/people/aaron_boley.png"
profile_url   = ""
role          = "Postdoc & Sagan Fellow, UF\nFaculty & CRC Chair, University of British Columbia"
bio           = ""
heading_level = "h3"
sort_order    = 4

[[links]]
url   = "https://www.aaronboley.com/"
title = "Personal Website"
icon  = "fa-solid fa-house"
