name         = "Daniel Carrera"
display_name  = "Daniel Carrera"
image         = "/assets/images/people/daniel_carrera.jpg"
profile_url   = ""
role          = "Postdoc, PSU\nAssistant Research Professor, New Mexico State University"
bio           = ""
heading_level = "h3"
sort_order    = 10

[[links]]
url   = "https://danielcarrera.space/"
title = "Personal Website"
icon  = "fa-solid fa-house"

[[links]]
url   = "https://scholar.google.co.uk/citations?user=FVus8WsAAAAJ"
title = "Google Scholar"
icon  = "fa-solid fa-graduation-cap"

[[links]]
url   = "https://github.com/dcarrera"
title = "GitHub"
icon  = "fab fa-github"
